// <auto-generated />
using System;
using System.Collections.Generic;
using GamerLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamerLog.Migrations
{
    [DbContext(typeof(GamerLogContext))]
    partial class GamerLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamerLog.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GamerLog.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("GamerLog.Entities.DigitalGame", b =>
                {
                    b.HasBaseType("GamerLog.Entities.Game");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ExternalIgdbId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("GenresId")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<long?>("ReleaseDateTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.ToTable("DigitalGames", (string)null);
                });

            modelBuilder.Entity("GamerLog.Entities.DigitalGame", b =>
                {
                    b.HasOne("GamerLog.Entities.Game", null)
                        .WithOne()
                        .HasForeignKey("GamerLog.Entities.DigitalGame", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
